@echo off
title 原神语音解包分类
echo 1.正在进行解包，该步骤需要较长时间，请耐心等待...
python 1_Unpack.py
chcp 936
echo 2.正在还原文件名...
python 2_Get_Filename.py -ver %1 -lang %2
echo 3.正在生成标注...
python 3_Get_DiffSinger_Label.py -ver %1 -lang %2
echo 4.正在分类语音...
python 4_Sorting.py -ver %1 -lang %2 -m mv
echo 5.正在二次整理...
python 5_Second_Sorting.py -lang %2
echo 6.正在清洗标注中的html标签...
python 6_Clean_Html_Tags.py -lang %2
echo 解包、分类完成！